apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    app: flask-ci-cd
spec:
  type: LoadBalancer
  selector:
    app: flask-ci-cd
  ports:
    - port: 80
      targetPort: 5000
  ports:
  - name: http     # ← ce nom est utilisé dans le ServiceMonitor
    port: 80
    targetPort: 5000
